[changelog]
body = """
# Version {{ version }} - {{ timestamp | date(format="%Y-%m-%d") }}

## Release highlights
{%- if commits | filter(attribute="group", value="feat") | length > 0 %}
{%- for commit in commits | filter(attribute="group", value="feat") %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- endfor %}
{%- else %}
- Minor improvements and maintenance updates.
{%- endif %}

## Added
{%- for commit in commits | filter(attribute="group", value="feat") %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- else %}
- No additions in this release.
{%- endfor %}

## Changed
{%- for commit in commits | filter(attribute="group", value="chore") %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- else %}
- No changes in this release.
{%- endfor %}

## Deprecated
{%- for commit in commits | filter(attribute="group", value="deprecate") %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- else %}
- No deprecations in this release.
{%- endfor %}

## Fixed
{%- for commit in commits | filter(attribute="group", value="fix") %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- else %}
- No fixes in this release.
{%- endfor %}

## Security
{%- for commit in commits | filter(attribute="group", value="security") %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- else %}
- No security updates in this release.
{%- endfor %}

## Breaking changes
{%- for commit in commits | filter(attribute="group", value="breaking") %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- else %}
- No breaking changes in this release.
{%- endfor %}

**Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}

{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
"""

trim = true

footer = """
<!-- generated by git-cliff -->
"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" }
]
filter_commits = false
topo_order = false
sort_commits = "newest"
