[target_information]
repo_path = "external_repos/EventFlow"
branch_name = "develop-v1"
start_commit = "1f5f3377099ff21d151e99c62e1fb7cc83dfe97c"
end_commit = "7c91526eaefd63887cb34072b81cfec50d63d598" #This need to be the latest commit between the two

[agents]

[[agents.output]]
result_path = "output/"
log_path = "logs/"
result_file_name = "changelog.md"

[[agents.orchestration]]
step = 1
model_name = "gemini-2.5-flash"
temperature = 0.2
template_path = "prompt/"
prompt_file = "orchestration.jinja"
prompt_variables = { name = "GitHub Docs", repo = "external_repos/EventFlow" }

[[agents.orchestration]]
step = 2
model_name = "gemini-2.5-flash"
temperature = 0.2
template_path = "prompt/"
prompt_file = "final.jinja"
prompt_variables = { name = "GitHub Docs", repo = "external_repos/EventFlow" }